### ISSUE TITLE
403 Errors

### ISSUE THREAD

**Issue by ndrewGele** [muhuk/python-awis#16]
Hey there, I'm getting an error when my script reaches the `api.url_info` step.
The error is: `IOError: All 3 requests failed, latest response code is 403`.
According to the troubleshooting tips from AWIS' other sample scripts, it could have something to do with my keys. One has a plus sign in it, but I'm not sure if that could be causing the issue or not.
Any thoughts?

**Comment by muhuk** [comment]
Hi @ndrewGele ,

Can you please provide a detailed description. Preferably a REPL session that demonstrates the error.
